version: '2.1'

services:
  vsftpd:
    build: ./vsftpd.lab1
    container_name: vsftpd
    ports:
    - "21:21"
    hostname: vsftpd
    volumes:
    - ./vsftpd.lab1/flag.txt:/root/flag.txt
    networks:
      DMZ-net:
        ipv4_address: 172.16.200.10
    command: vsftpd 
    command: tail -f /dev/null

networks:
  DMZ-net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.200.0/24
        gateway: 172.16.200.3
#  target-net:
#    driver: bridge
#    driver_opts:
#      com.docker.network.enable_ipv6: "false"
#    ipam:
#      driver: default
#      config:
#      - subnet: 172.16.201.0/24
#        gateway: 172.16.201.3

